### PR TITLE
Enable cors header for API

### PR DESCRIPTION
**Pull request by remybach**
I hope you don't mind, but I took the liberty of adding what I think is needed for this. My PHP is a bit rusty, and I'm not sure how to test this without putting it live and seeing if it works.

Edit: this is in relation to #34.

### CODE REVIEW

**Comment by BinarMorker** [comment]
Thank you, I don't really have the time to work on the website myself these days.

The change has gone live, so you should be able to try it.
I also took the time to fix some priority speed issue on the website and API.

Tell me if it works!

**Comment by remybach** [comment]
Ah, that's great... thanks so much! I've tested it and it seems to be working now \\o/

**Comment by remybach** [comment]
Just FYI, here's what I created using your API: https://remybach.github.io/destiny-return-on-investment

I'll be posting it on /r/destinythegame in a few hours' time, so I thought I'd give you a heads up 😄

**Comment by BinarMorker** [comment]
I love it!

That's an awesome website you,ve made. Just for your information, Bungie's
API might change with Destiny 2, so I'll try to keep mine as close as
possible but I might have to change a couple things. I'll keep you updated
and provide you with some documentation if I have to change it.

**Comment by remybach** [comment]
Thanks!

Yeah, I'm totally expecting that - in fact, I've worked with the API in the past, so I _hope_ they actually update it!

I can only dream of a lovely REST based JSON API 😍

**Pull request merged**
